# Generated by Django 5.1.1 on 2024-09-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, unique=True)),
                ('timestamp', models.DateField(auto_now=True)),
                ('weather_details', models.JSONField()),
                ('forecast_details', models.JSONField()),
            ],
        ),
    ]
