# Generated by Django 5.1.1 on 2024-09-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=128)),
                ('app_logo', models.ImageField(null=True, upload_to='app')),
                ('api_key', models.CharField(max_length=128, null=True)),
                ('forecast_days', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='weatherdetails',
            name='previous_details',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='weatherdetails',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
