# Generated by Django 5.1.1 on 2024-09-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appsetting_weatherdetails_previous_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsetting',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='appsetting',
            name='app_logo',
        ),
        migrations.RemoveField(
            model_name='appsetting',
            name='app_name',
        ),
        migrations.AddField(
            model_name='appsetting',
            name='threshold_values',
            field=models.JSONField(null=True),
        ),
    ]
